nodeLinker: node-modules
 
npmAlwaysAuth: true
npmAuthToken: "${ORXCORE_NPM_TOKEN}"
npmRegistryServer: "https://edgeinternal1uhg.optum.com/artifactory/api/npm/orxcore-npm-vir/"
  
supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
 
# you may need to comment this line out if you are on a windows machine
yarnPath: .yarn/releases/yarn-3.2.0.cjs
 