sonar.login=
sonar.projectName=
sonar.application.askkey=
sonar.projectKey=

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sources=packages,surfaces
sonar.test.inclusions=**/*.test.tsx
sonar.sourceEncoding=UTF-8
sonar.buildbreaker.skip=true
sonar.typescript.exclusions='*.svg,*.css,**/index.tsx,**/tsconfig.json
sonar.exclusions=node_modules/**, **/*.stories.tsx, *.svg,*.css,types/**,tools/**,docs/**,**/*.java
sonar.yaml.exclusions='vitals.yaml'
sonar.typescript.tsconfigPath=tsconfig.json