name: Release Minor

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: Name of the release (should match 'rel_YYYY_1-12' 'rel_2023_2')
        required: true

jobs:
  release_minor:
    name: Release Minor
    runs-on: uhg-runner
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          # Need to fetch entire repo history to do proper versioning
          fetch_depth: 0
          # If you have a protected main branch then add this value as a secret and uncomment
          # token: ${{ secrets.GH_PUSH_TO_PROTECTED_BRANCH_PAT }}
          skip_gh_install: true

      - name: Configure Git
        uses: ./.github/actions/configure-git-identity
        with:
          workflow_name: publish-release-versions

      - name: Bump Version Numbers
        run: |
          echo "Bumping changed package version numbers and pushing to remote"
          npx @optum-rx-platform/cli@latest run-script release --minor --quiet

      - name: Create new branch
        run: |
          git checkout -b ${{ inputs.release_name }}
          git push --set-upstream origin ${{ inputs.release_name }} --no-verify

      - name: Archive CDN artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: cdn-dist-files
          path: cdn-dist

      - name: Archive NPM artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: npm-dist-files
          path: npm-dist

      - name: Archive Container artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: container-dist-files
          path: container-dist

      - name: Archive Logs artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: logs-files
          path: logs
